#!/bin/sh

# start network manager
    sleep 1 &&
    nm-applet &

# enable bluetooth applet
    sleep 1 &&
    blueman-applet &

#wallpaper
#    feh --bg-fil /home/shatterstone/wallpapers/bliss.jpg

#pcmanfm for desktop icons (also sets wallpaper)
    sleep 1 &&
    pcmanfm --desktop &
