#!/usr/bin/env sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

# bspc config split_ratio          0.50
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true
# bspc config pointer_follows_focus false
# bspc focus_follows_pointer true
# bspc click_to_focus any

bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color           "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#### MONITORS ####
for monitor in $(bspc query -M)
do
    # set the workspaces on each monitor to 1-9
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9
    #polybar hidden when fullscreen for vlc, youtube, mpv ...
    xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_$monitor)
done

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a blueberry.py state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a blueman state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bsp-layout set tall 1 --master-size 0.5 &
bsp-layout set tall 2 --master-size 0.5 &
bsp-layout set tall 3 --master-size 0.5 &
bsp-layout set tall 4 --master-size 0.5 &
bsp-layout set tall 5 --master-size 0.5 &
bsp-layout set tall 6 --master-size 0.5 &
bsp-layout set tall 7 --master-size 0.5 &
bsp-layout set tall 8 --master-size 0.5 &
bsp-layout set tall 9 --master-size 0.5 &
sxhkd &
picom --config $HOME/.config/picom.conf &
#feh --bg-fill $HOME/wallpapers/105.jpg &
feh --bg-fill --randomize $HOME/wallpapers/ &
dunst &
xsetroot -cursor_name left_ptr &
polybar bspwm &

