font_family      Hack 
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

force_ltr no

cursor_shape beam

disable_ligatures never

confirm_os_window_close  0

font_features none

background_opacity 0.9

foreground #f9f9f9
background #222222

#black
color0 #3f3f3f
color8 #545454

# red
color1   #fc5454
color9   #fc5454

# green
color2    #4e9a06
color10   #8ae234

# yellow
color3    #c4a000
color11   #fce94f

# blue
color4   #94bff3
color12  #94bff3

# magenta
color5   #85678f
color13  #b294bb

# cyan
color6   #06989a
color14  #93e0e3

# white
color7   #dcdccc
color15  #ffffff
